export const AMENITIES = [
  { id: 'a1', name: 'Wi-Fi', icon: 'wifi' },
  { id: 'a2', name: 'AC', icon: 'thermometer-sun' },
  { id: 'a3', name: 'Covered Parking', icon: 'car' },
  { id: 'a4', name: 'Open Parking', icon: 'car-front' },
  { id: 'a5', name: 'Power Backup', icon: 'zap' },
  { id: 'a6', name: 'Security', icon: 'shield' },
  { id: 'a7', name: 'Intercom', icon: 'phone' },
  { id: 'a8', name: 'Lift', icon: 'arrow-up-down' },
  { id: 'a9', name: 'Gym', icon: 'dumbbell' },
  { id: 'a10', name: 'Swimming Pool', icon: 'waves' },
  { id: 'a11', name: 'Fully Furnished', icon: 'sofa' },
  { id: 'a12', name: 'Semi Furnished', icon: 'bed' }
];

export const PROPERTIES = [
  {
    id: 'p7',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    title: 'Samanvay Aasra',
    project: 'Samanvay Aasra',
    location: 'Mahapura, Ajmer Road, Jaipur',
    configuration: '2 BHK',
    type: 'Apartment',
    areaSqFt: 850,
    floor: '5th of 10',
    bathrooms: 2,
    balconies: 1,
    furnishing: 'Semi Furnished',
    parking: '1 Covered Parking',
    rent: 14000,
    securityDeposit: 14000,
    maintenance: 1200,
    electricity: 0,
    internet: 0,
    availability: 'Available now',
    leaseType: 'Family / Bachelor',
    amenities: ['a1', 'a2', 'a3', 'a6', 'a8'],
    coordinates: { lat: 26.8380368, lng: 75.6546479 },
    distanceKm: '0.6',
    source: 'Local Listing',
    sourceUrl: 'https://www.google.com/maps/place/Samanvay+Aasra',
    checkedAt: 'Oct 6, 2026',
    verifiedByUniNest: true,
    housingScore: 88
  },
  {
    id: 'p8',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1de2d96674?auto=format&fit=crop&w=800&q=80',
    title: 'Samanvay The New Door',
    project: 'Samanvay The New Door',
    location: 'Mahindra SEZ, Jaipur',
    configuration: '3 BHK',
    type: 'Apartment',
    areaSqFt: 1450,
    floor: '8th of 14',
    bathrooms: 3,
    balconies: 2,
    furnishing: 'Fully Furnished',
    parking: '2 Covered Parking',
    rent: 22000,
    securityDeposit: 44000,
    maintenance: 2500,
    electricity: 0,
    internet: 0,
    availability: 'Available from Nov 1',
    leaseType: 'Family / Company',
    amenities: ['a1', 'a2', 'a3', 'a5', 'a6', 'a8', 'a9', 'a10', 'a11'],
    coordinates: { lat: 26.8293025, lng: 75.654102 },
    distanceKm: '2.1',
    source: 'Local Listing',
    sourceUrl: 'https://www.google.com/maps/place/Samanvay+The+New+Door',
    checkedAt: 'Oct 6, 2026',
    verifiedByUniNest: true,
    housingScore: 92
  },
  {
    id: 'p9',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    title: 'Ashiana Umang Phase II',
    project: 'Ashiana Umang',
    location: 'Near JKLU, Mahapura, Jaipur',
    configuration: '2 BHK',
    type: 'Apartment',
    areaSqFt: 1100,
    floor: '1st of 5',
    bathrooms: 2,
    balconies: 1,
    furnishing: 'Semi Furnished',
    parking: '1 Open Parking',
    rent: 16000,
    securityDeposit: 32000,
    maintenance: 1500,
    electricity: 0,
    internet: 0,
    availability: 'Available now',
    leaseType: 'Family / Bachelor',
    amenities: ['a4', 'a6', 'a12'],
    coordinates: { lat: 26.8267777, lng: 75.6577877 },
    distanceKm: '1.5',
    source: 'Local Listing',
    sourceUrl: '#',
    checkedAt: 'Oct 6, 2026',
    verifiedByUniNest: true,
    housingScore: 85
  },
  {
    id: 'p1',
    title: 'Vardhman Empire Estate',
    project: 'Vardhman Empire Estate',
    location: 'Mahapura, Ajmer Road, Jaipur',
    configuration: '1 BHK',
    type: 'Apartment',
    areaSqFt: 446,
    floor: '2nd of 12',
    bathrooms: 1,
    balconies: 1,
    furnishing: 'Fully Furnished',
    parking: '1 Open Parking',
    rent: 15000,
    securityDeposit: 15000,
    maintenance: 'Not disclosed',
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Available now',
    leaseType: 'Family / Bachelor / Company',
    amenities: ['a4', 'a11'],
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.837, lng: 75.659 },
    distanceKm: '1.2',
    source: 'Local Listing',
    listingUpdated: 'Sep 30, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: false,
    landlordId: null
  },
  {
    id: 'p2',
    title: 'Vardhman Empire Estate Premium',
    project: 'Vardhman Empire Estate',
    location: 'Mahapura, Ajmer Road, Jaipur',
    configuration: '3 BHK',
    type: 'Apartment',
    areaSqFt: 920,
    floor: 'Not disclosed',
    bathrooms: 2,
    balconies: 1,
    furnishing: 'Fully Furnished',
    parking: 'Not disclosed',
    rent: 16000,
    securityDeposit: 16000,
    maintenance: 'Not disclosed',
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Available now',
    leaseType: 'Not disclosed',
    amenities: ['a11'],
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1de2d96674?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.837, lng: 75.659 },
    distanceKm: '1.2',
    source: 'Local Listing',
    listingUpdated: 'Sep 25, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: false,
    landlordId: null
  },
  {
    id: 'p3',
    title: 'Vardhman Empire Estate Luxury',
    project: 'Vardhman Empire Estate',
    location: 'Mahapura, Ajmer Road, Jaipur',
    configuration: '3 BHK',
    type: 'Apartment',
    areaSqFt: 926,
    floor: '2nd of 14',
    bathrooms: 2,
    balconies: 2,
    furnishing: 'Fully Furnished',
    parking: '1 Covered + 3 Open Parking',
    rent: 30000,
    securityDeposit: 30000,
    maintenance: 'Not disclosed',
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Available now',
    leaseType: 'Not disclosed',
    amenities: ['a3', 'a4', 'a11'],
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.837, lng: 75.659 },
    distanceKm: '1.2',
    source: 'Local Listing',
    listingUpdated: 'Oct 1, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: true,
    landlordId: 'l1'
  },
  {
    id: 'p4',
    title: 'Vardhman Empire Estate Highrise',
    project: 'Vardhman Empire Estate',
    location: 'Mahapura, Ajmer Road, Jaipur',
    configuration: '1 BHK',
    type: 'Apartment',
    areaSqFt: 360,
    carpetAreaSqFt: 355,
    floor: '11th of 14',
    bathrooms: 1,
    balconies: 1,
    furnishing: 'Fully Furnished',
    parking: '1 Covered Parking',
    rent: 15800,
    securityDeposit: 15800,
    maintenance: 'Not disclosed',
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Available from Sep 2026',
    leaseType: 'Not disclosed',
    amenities: ['a3', 'a11'],
    imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.837, lng: 75.659 },
    distanceKm: '1.2',
    source: 'Local Listing',
    listingUpdated: 'Aug 20, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: false,
    landlordId: null
  },
  {
    id: 'p5',
    title: 'Ashiana Umang Residences',
    project: 'Ashiana Umang',
    location: 'Near Mahindra SEZ, Ajmer Road, Jaipur',
    configuration: '2 BHK',
    type: 'Apartment',
    areaSqFt: 1175,
    floor: '4th',
    bathrooms: 2,
    balconies: 1,
    furnishing: 'Not disclosed',
    parking: 'Covered Parking',
    rent: 15000,
    securityDeposit: 'Not disclosed',
    maintenance: 4000,
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Not disclosed',
    leaseType: 'Not disclosed',
    amenities: ['a3', 'a5', 'a6', 'a7'],
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.821, lng: 75.642 },
    distanceKm: '3.8',
    source: 'Landlord Submitted',
    listingUpdated: 'Oct 2, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: false,
    landlordId: null
  },
  {
    id: 'p6',
    title: 'Mahima Nirvana Tower A',
    project: 'Mahima Nirvana',
    location: 'Mahapura, Jaipur',
    configuration: '3 BHK',
    type: 'Apartment',
    areaSqFt: 1450,
    floor: '6th',
    bathrooms: 3,
    balconies: 2,
    furnishing: 'Semi Furnished',
    parking: '1 Covered Parking',
    rent: 22000,
    securityDeposit: 44000,
    maintenance: 3000,
    electricity: 'Not disclosed',
    internet: 'Not disclosed',
    availability: 'Available now',
    leaseType: 'Family / Students',
    amenities: ['a3', 'a5', 'a6', 'a8', 'a9', 'a10', 'a12'],
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.839, lng: 75.650 },
    distanceKm: '1.5',
    source: 'Local Network',
    listingUpdated: 'Oct 4, 2026',
    checkedAt: 'Oct 6, 2026',
    status: 'Listing found',
    verifiedByUniNest: true,
    landlordId: 'l2'
  }
];

export const STUDENTS = [
  {
    id: 's1',
    name: 'Rahul Mehta',
    email: 'rahul.m@jklu.edu.in',
    course: 'B.Tech CSE',
    year: 2,
    gender: 'Male',
    verified: true,
    preferences: {
      budgetMin: 7000,
      budgetMax: 10000,
      sleepTime: '11:30 PM',
      wakeTime: '7:30 AM',
      cleanliness: 'High',
      noiseTolerance: 'Low',
      studyHabits: 'Focused',
      foodPreference: 'Either',
      smoking: 'Non-smoker',
      guestPreference: 'Occasional',
      ac: true
    }
  },
  {
    id: 's2',
    name: 'Current User',
    email: 'demo.student@jklu.edu.in',
    course: 'B.Tech CSE',
    year: 2,
    gender: 'Male',
    verified: true,
    preferences: {
      budgetMin: 8000,
      budgetMax: 12000,
      sleepTime: '11:30 PM',
      wakeTime: '8:00 AM',
      cleanliness: 'High',
      noiseTolerance: 'Low',
      studyHabits: 'Focused',
      foodPreference: 'Either',
      smoking: 'Non-smoker',
      guestPreference: 'Occasional',
      ac: true
    }
  },
  { id: 's3', name: 'Aarav Jain', course: 'BBA', year: 1, gender: 'Male', verified: true, preferences: { budgetMin: 6000, budgetMax: 9000, sleepTime: '1:00 AM', wakeTime: '9:00 AM', cleanliness: 'Medium', noiseTolerance: 'Medium', studyHabits: 'Casual', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Frequent', ac: false } },
  { id: 's4', name: 'Riya Sharma', course: 'B.Des', year: 3, gender: 'Female', verified: true, preferences: { budgetMin: 9000, budgetMax: 15000, sleepTime: '10:30 PM', wakeTime: '6:30 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: true } },
  { id: 's5', name: 'Dev Kapoor', course: 'B.Tech CSE', year: 4, gender: 'Male', verified: true, preferences: { budgetMin: 8000, budgetMax: 12000, sleepTime: '2:00 AM', wakeTime: '10:00 AM', cleanliness: 'Low', noiseTolerance: 'High', studyHabits: 'Casual', foodPreference: 'Non-veg', smoking: 'Smoker', guestPreference: 'Frequent', ac: true } },
  { id: 's6', name: 'Kunal Saini', course: 'B.Tech ECE', year: 2, gender: 'Male', verified: true, preferences: { budgetMin: 7000, budgetMax: 10000, sleepTime: '11:00 PM', wakeTime: '7:00 AM', cleanliness: 'High', noiseTolerance: 'Medium', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } }
];

export const MATCHES = [
  { id: 'm1', s1: 's2', s2: 's1', budgetScore: 100, lifestyleScore: 92, housingScore: 95, overallScore: 94, status: 'Pending', matchedOn: '2026-10-01' },
  { id: 'm2', s1: 's2', s2: 's3', budgetScore: 85, lifestyleScore: 70, housingScore: 80, overallScore: 75, status: 'Rejected', matchedOn: '2026-10-02' }
];

export const LANDLORDS = [
  { id: 'l1', name: 'Ramesh Singh', email: 'ramesh.s@example.com', verified: true, phone: 'Not disclosed' },
  { id: 'l2', name: 'Sunita Sharma', email: 'sunita.s@example.com', verified: true, phone: 'Not disclosed' }
];

export const calculateKnownMonthlyCost = (property: any) => {
  let cost = property.rent || 0;
  if (typeof property.maintenance === 'number') cost += property.maintenance;
  if (typeof property.electricity === 'number') cost += property.electricity;
  if (typeof property.internet === 'number') cost += property.internet;
  return cost;
};

export const hasUndisclosedCosts = (property: any) => {
  return property.maintenance === 'Not disclosed' || property.electricity === 'Not disclosed' || property.internet === 'Not disclosed';
};

export const LEASES = [
  { id: 'lease1', propertyId: 'p3', studentIds: ['s1', 's2'], landlordId: 'l1', startDate: '2026-08-01', endDate: '2027-07-31', rent: 30000, status: 'Active' },
  { id: 'lease2', propertyId: 'p6', studentIds: ['s4', 's6'], landlordId: 'l2', startDate: '2026-09-01', endDate: '2027-08-31', rent: 22000, status: 'Active' }
];
