// src/lib/data.ts

export const AMENITIES = [
  { id: 'a1', name: 'Wi-Fi', icon: 'wifi' },
  { id: 'a2', name: 'AC', icon: 'thermometer-sun' },
  { id: 'a3', name: 'Parking', icon: 'car' },
  { id: 'a4', name: 'Kitchen', icon: 'utensils' },
  { id: 'a5', name: 'Washing Machine', icon: 'shirt' },
  { id: 'a6', name: 'Power Backup', icon: 'zap' },
  { id: 'a7', name: 'Attached Bathroom', icon: 'bath' },
  { id: 'a8', name: 'Gym', icon: 'dumbbell' },
  { id: 'a9', name: 'Security', icon: 'shield' },
  { id: 'a10', name: 'Furnished', icon: 'sofa' }
];

export const PROPERTIES = [
  {
    id: 'p1',
    title: 'JKLU Student Residence Premium',
    type: '3 BHK Shared',
    location: 'Mahapura',
    distance: 1.2,
    verified: true,
    rating: 4.8,
    totalSlots: 6,
    availableSlots: 2,
    rent: 8000,
    electricity: 500,
    internet: 300,
    maintenance: 650,
    deposit: 16000,
    gender: 'Male',
    amenities: ['a1', 'a2', 'a4', 'a5', 'a7', 'a10'],
    coordinates: { lat: 26.837, lng: 75.659 },
    landlordId: 'l1',
    status: 'active'
  },
  {
    id: 'p2',
    title: 'Ajmer Road Shared Flat',
    type: '2 BHK Shared',
    location: 'Ajmer Road',
    distance: 3.5,
    verified: true,
    rating: 4.5,
    totalSlots: 4,
    availableSlots: 1,
    rent: 7500,
    electricity: 600,
    internet: 250,
    maintenance: 500,
    deposit: 15000,
    gender: 'Female',
    amenities: ['a1', 'a4', 'a6', 'a10'],
    coordinates: { lat: 26.845, lng: 75.672 },
    landlordId: 'l2',
    status: 'active'
  },
  {
    id: 'p3',
    title: 'Quiet Study Private Room',
    type: 'Private Room',
    location: 'Mahapura Village',
    distance: 0.8,
    verified: true,
    rating: 4.9,
    totalSlots: 1,
    availableSlots: 1,
    rent: 11000,
    electricity: 800,
    internet: 400,
    maintenance: 400,
    deposit: 22000,
    gender: 'Any',
    amenities: ['a1', 'a2', 'a7', 'a10', 'a6'],
    coordinates: { lat: 26.832, lng: 75.655 },
    landlordId: 'l3',
    status: 'active'
  },
  {
    id: 'p4',
    title: 'Mahindra SEZ Premium Apartments',
    type: '4 BHK Shared',
    location: 'Mahindra SEZ',
    distance: 5.2,
    verified: true,
    rating: 4.7,
    totalSlots: 8,
    availableSlots: 3,
    rent: 9000,
    electricity: 400,
    internet: 200,
    maintenance: 1200,
    deposit: 18000,
    gender: 'Male',
    amenities: ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10'],
    coordinates: { lat: 26.820, lng: 75.640 },
    landlordId: 'l1',
    status: 'active'
  },
  {
    id: 'p5',
    title: 'Campus View Residency',
    type: '2 BHK Shared',
    location: 'Mahapura',
    distance: 0.5,
    verified: false,
    rating: 4.2,
    totalSlots: 4,
    availableSlots: 4,
    rent: 6500,
    electricity: 500,
    internet: 300,
    maintenance: 300,
    deposit: 13000,
    gender: 'Female',
    amenities: ['a1', 'a4', 'a10'],
    coordinates: { lat: 26.839, lng: 75.662 },
    landlordId: 'l4',
    status: 'active'
  },
  // Add 10 more to meet the 15+ requirement...
  {
    id: 'p6',
    title: 'Green Valley Homes',
    type: '3 BHK Shared',
    location: 'Ajmer Road',
    distance: 4.1,
    verified: true,
    rating: 4.6,
    totalSlots: 6,
    availableSlots: 2,
    rent: 7200,
    electricity: 450,
    internet: 300,
    maintenance: 400,
    deposit: 14400,
    gender: 'Male',
    amenities: ['a1', 'a4', 'a5', 'a9'],
    coordinates: { lat: 26.850, lng: 75.680 },
    landlordId: 'l2',
    status: 'active'
  },
  {
    id: 'p7',
    title: 'Sunrise Apartments',
    type: '2 BHK Private',
    location: 'Mahapura',
    distance: 1.5,
    verified: true,
    rating: 4.4,
    totalSlots: 2,
    availableSlots: 0,
    rent: 12000,
    electricity: 600,
    internet: 400,
    maintenance: 800,
    deposit: 24000,
    gender: 'Female',
    amenities: ['a1', 'a2', 'a3', 'a7', 'a9'],
    coordinates: { lat: 26.835, lng: 75.650 },
    landlordId: 'l3',
    status: 'active'
  },
  {
    id: 'p8',
    title: 'Oasis Student Living',
    type: '1 RK',
    location: 'Mahapura Village',
    distance: 1.0,
    verified: true,
    rating: 4.3,
    totalSlots: 1,
    availableSlots: 1,
    rent: 8500,
    electricity: 300,
    internet: 200,
    maintenance: 200,
    deposit: 17000,
    gender: 'Any',
    amenities: ['a1', 'a4', 'a7'],
    coordinates: { lat: 26.834, lng: 75.658 },
    landlordId: 'l5',
    status: 'active'
  },
  {
    id: 'p9',
    title: 'Elite Residency',
    type: '3 BHK Shared',
    location: 'Mahindra SEZ',
    distance: 6.0,
    verified: false,
    rating: 4.0,
    totalSlots: 6,
    availableSlots: 5,
    rent: 8800,
    electricity: 500,
    internet: 250,
    maintenance: 1000,
    deposit: 17600,
    gender: 'Male',
    amenities: ['a1', 'a2', 'a3', 'a8', 'a10'],
    coordinates: { lat: 26.815, lng: 75.635 },
    landlordId: 'l4',
    status: 'active'
  },
  {
    id: 'p10',
    title: 'JKLU Hub',
    type: '4 BHK Shared',
    location: 'Mahapura',
    distance: 0.3,
    verified: true,
    rating: 4.8,
    totalSlots: 8,
    availableSlots: 0,
    rent: 9500,
    electricity: 600,
    internet: 350,
    maintenance: 500,
    deposit: 19000,
    gender: 'Male',
    amenities: ['a1', 'a2', 'a4', 'a5', 'a6', 'a7'],
    coordinates: { lat: 26.840, lng: 75.663 },
    landlordId: 'l1',
    status: 'active'
  },
  {
    id: 'p11',
    title: 'Cozy Corner Flat',
    type: '2 BHK Shared',
    location: 'Ajmer Road',
    distance: 2.8,
    verified: true,
    rating: 4.1,
    totalSlots: 4,
    availableSlots: 2,
    rent: 6800,
    electricity: 400,
    internet: 200,
    maintenance: 300,
    deposit: 13600,
    gender: 'Female',
    amenities: ['a1', 'a4'],
    coordinates: { lat: 26.842, lng: 75.668 },
    landlordId: 'l5',
    status: 'active'
  },
  {
    id: 'p12',
    title: 'Scholars Den',
    type: '3 BHK Shared',
    location: 'Mahapura',
    distance: 1.8,
    verified: true,
    rating: 4.5,
    totalSlots: 6,
    availableSlots: 3,
    rent: 7800,
    electricity: 500,
    internet: 300,
    maintenance: 450,
    deposit: 15600,
    gender: 'Female',
    amenities: ['a1', 'a2', 'a4', 'a6', 'a9'],
    coordinates: { lat: 26.830, lng: 75.652 },
    landlordId: 'l2',
    status: 'active'
  },
  {
    id: 'p13',
    title: 'Urban Loft',
    type: '1 BHK',
    location: 'Mahindra SEZ',
    distance: 4.5,
    verified: true,
    rating: 4.7,
    totalSlots: 2,
    availableSlots: 1,
    rent: 14000,
    electricity: 800,
    internet: 500,
    maintenance: 1500,
    deposit: 28000,
    gender: 'Any',
    amenities: ['a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a10'],
    coordinates: { lat: 26.825, lng: 75.645 },
    landlordId: 'l3',
    status: 'active'
  },
  {
    id: 'p14',
    title: 'Budget Stay Mahapura',
    type: '3 BHK Shared',
    location: 'Mahapura Village',
    distance: 2.0,
    verified: false,
    rating: 3.8,
    totalSlots: 6,
    availableSlots: 4,
    rent: 5500,
    electricity: 300,
    internet: 200,
    maintenance: 200,
    deposit: 11000,
    gender: 'Male',
    amenities: ['a1', 'a4'],
    coordinates: { lat: 26.828, lng: 75.660 },
    landlordId: 'l4',
    status: 'active'
  },
  {
    id: 'p15',
    title: 'Premium Studio Ajmer Rd',
    type: 'Studio',
    location: 'Ajmer Road',
    distance: 3.2,
    verified: true,
    rating: 4.9,
    totalSlots: 1,
    availableSlots: 1,
    rent: 16000,
    electricity: 1000,
    internet: 600,
    maintenance: 1200,
    deposit: 32000,
    gender: 'Any',
    amenities: ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a9', 'a10'],
    coordinates: { lat: 26.848, lng: 75.675 },
    landlordId: 'l1',
    status: 'active'
  }
];

export const STUDENTS = [
  {
    id: 's1',
    name: 'Rahul Mehta',
    email: 'rahul.m@jklu.edu.in',
    course: 'B.Tech CSE',
    year: 2,
    gender: 'Male',
    verified: true,
    preferences: {
      budgetMin: 7000,
      budgetMax: 10000,
      sleepTime: '11:30 PM',
      wakeTime: '7:30 AM',
      cleanliness: 'High',
      noiseTolerance: 'Low',
      studyHabits: 'Focused',
      foodPreference: 'Either',
      smoking: 'Non-smoker',
      guestPreference: 'Occasional',
      ac: true
    }
  },
  {
    id: 's2',
    name: 'Current User', // The demo logged-in user
    email: 'demo.student@jklu.edu.in',
    course: 'B.Tech CSE',
    year: 2,
    gender: 'Male',
    verified: true,
    preferences: {
      budgetMin: 8000,
      budgetMax: 12000,
      sleepTime: '11:30 PM',
      wakeTime: '8:00 AM',
      cleanliness: 'High',
      noiseTolerance: 'Low',
      studyHabits: 'Focused',
      foodPreference: 'Either',
      smoking: 'Non-smoker',
      guestPreference: 'Occasional',
      ac: true
    }
  },
  // Adding more students to reach 20...
  { id: 's3', name: 'Aarav Sharma', course: 'BBA', year: 1, gender: 'Male', verified: true, preferences: { budgetMin: 6000, budgetMax: 9000, sleepTime: '1:00 AM', wakeTime: '9:00 AM', cleanliness: 'Medium', noiseTolerance: 'Medium', studyHabits: 'Casual', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Frequent', ac: false } },
  { id: 's4', name: 'Priya Patel', course: 'B.Des', year: 3, gender: 'Female', verified: true, preferences: { budgetMin: 9000, budgetMax: 15000, sleepTime: '10:30 PM', wakeTime: '6:30 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: true } },
  { id: 's5', name: 'Aditya Singh', course: 'B.Tech CSE', year: 4, gender: 'Male', verified: true, preferences: { budgetMin: 8000, budgetMax: 12000, sleepTime: '2:00 AM', wakeTime: '10:00 AM', cleanliness: 'Low', noiseTolerance: 'High', studyHabits: 'Casual', foodPreference: 'Non-veg', smoking: 'Smoker', guestPreference: 'Frequent', ac: true } },
  { id: 's6', name: 'Neha Gupta', course: 'B.Tech ECE', year: 2, gender: 'Female', verified: true, preferences: { budgetMin: 7000, budgetMax: 10000, sleepTime: '11:00 PM', wakeTime: '7:00 AM', cleanliness: 'High', noiseTolerance: 'Medium', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's7', name: 'Karan Verma', course: 'BBA', year: 2, gender: 'Male', verified: false, preferences: { budgetMin: 5000, budgetMax: 8000, sleepTime: '12:00 AM', wakeTime: '8:00 AM', cleanliness: 'Medium', noiseTolerance: 'High', studyHabits: 'Casual', foodPreference: 'Either', smoking: 'Non-smoker', guestPreference: 'Frequent', ac: false } },
  { id: 's8', name: 'Riya Jain', course: 'B.Des', year: 1, gender: 'Female', verified: true, preferences: { budgetMin: 10000, budgetMax: 18000, sleepTime: '11:30 PM', wakeTime: '8:30 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's9', name: 'Vikram Reddy', course: 'M.Tech CSE', year: 1, gender: 'Male', verified: true, preferences: { budgetMin: 8000, budgetMax: 13000, sleepTime: '12:30 AM', wakeTime: '8:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Non-veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: true } },
  { id: 's10', name: 'Sneha Rao', course: 'B.Tech CSE', year: 3, gender: 'Female', verified: true, preferences: { budgetMin: 7500, budgetMax: 11000, sleepTime: '10:00 PM', wakeTime: '6:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: true } },
  { id: 's11', name: 'Arjun Das', course: 'BBA', year: 3, gender: 'Male', verified: true, preferences: { budgetMin: 6000, budgetMax: 10000, sleepTime: '1:30 AM', wakeTime: '9:30 AM', cleanliness: 'Medium', noiseTolerance: 'Medium', studyHabits: 'Casual', foodPreference: 'Either', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: false } },
  { id: 's12', name: 'Pooja Mishra', course: 'B.Tech ECE', year: 4, gender: 'Female', verified: true, preferences: { budgetMin: 8000, budgetMax: 12000, sleepTime: '11:00 PM', wakeTime: '7:30 AM', cleanliness: 'High', noiseTolerance: 'Medium', studyHabits: 'Focused', foodPreference: 'Either', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's13', name: 'Rohan Kumar', course: 'B.Des', year: 2, gender: 'Male', verified: false, preferences: { budgetMin: 9000, budgetMax: 14000, sleepTime: '2:30 AM', wakeTime: '10:30 AM', cleanliness: 'Medium', noiseTolerance: 'High', studyHabits: 'Casual', foodPreference: 'Non-veg', smoking: 'Smoker', guestPreference: 'Frequent', ac: true } },
  { id: 's14', name: 'Ananya Desai', course: 'B.Tech CSE', year: 1, gender: 'Female', verified: true, preferences: { budgetMin: 7000, budgetMax: 10500, sleepTime: '11:00 PM', wakeTime: '7:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: true } },
  { id: 's15', name: 'Deepak Joshi', course: 'M.Tech CSE', year: 2, gender: 'Male', verified: true, preferences: { budgetMin: 10000, budgetMax: 16000, sleepTime: '12:00 AM', wakeTime: '8:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Either', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's16', name: 'Sanya Kapoor', course: 'BBA', year: 1, gender: 'Female', verified: true, preferences: { budgetMin: 8500, budgetMax: 13000, sleepTime: '12:30 AM', wakeTime: '9:00 AM', cleanliness: 'Medium', noiseTolerance: 'Medium', studyHabits: 'Casual', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Frequent', ac: true } },
  { id: 's17', name: 'Manish Tiwari', course: 'B.Tech ECE', year: 1, gender: 'Male', verified: false, preferences: { budgetMin: 5500, budgetMax: 8500, sleepTime: '11:00 PM', wakeTime: '7:30 AM', cleanliness: 'Medium', noiseTolerance: 'Medium', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: false } },
  { id: 's18', name: 'Kritika Sen', course: 'B.Des', year: 4, gender: 'Female', verified: true, preferences: { budgetMin: 11000, budgetMax: 18000, sleepTime: '1:00 AM', wakeTime: '9:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Either', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's19', name: 'Yash Agarwal', course: 'B.Tech CSE', year: 3, gender: 'Male', verified: true, preferences: { budgetMin: 7500, budgetMax: 11500, sleepTime: '11:30 PM', wakeTime: '8:00 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Occasional', ac: true } },
  { id: 's20', name: 'Isha Nair', course: 'BBA', year: 2, gender: 'Female', verified: true, preferences: { budgetMin: 6500, budgetMax: 9500, sleepTime: '10:30 PM', wakeTime: '6:30 AM', cleanliness: 'High', noiseTolerance: 'Low', studyHabits: 'Focused', foodPreference: 'Veg', smoking: 'Non-smoker', guestPreference: 'Rare', ac: false } }
];

export const MATCHES = [
  { id: 'm1', s1: 's2', s2: 's1', budgetScore: 100, lifestyleScore: 92, housingScore: 95, overallScore: 94, status: 'Pending', matchedOn: '2023-10-01' },
  { id: 'm2', s1: 's2', s2: 's9', budgetScore: 95, lifestyleScore: 88, housingScore: 90, overallScore: 89, status: 'Accepted', matchedOn: '2023-10-02' },
  { id: 'm3', s1: 's2', s2: 's15', budgetScore: 80, lifestyleScore: 95, housingScore: 90, overallScore: 91, status: 'Pending', matchedOn: '2023-10-05' },
  { id: 'm4', s1: 's2', s2: 's19', budgetScore: 100, lifestyleScore: 100, housingScore: 95, overallScore: 97, status: 'Pending', matchedOn: '2023-10-06' },
  { id: 'm5', s1: 's4', s2: 's8', budgetScore: 90, lifestyleScore: 85, housingScore: 95, overallScore: 89, status: 'Accepted', matchedOn: '2023-09-25' },
  { id: 'm6', s1: 's6', s2: 's10', budgetScore: 100, lifestyleScore: 95, housingScore: 90, overallScore: 94, status: 'Accepted', matchedOn: '2023-09-28' },
  { id: 'm7', s1: 's3', s2: 's7', budgetScore: 85, lifestyleScore: 70, housingScore: 80, overallScore: 75, status: 'Rejected', matchedOn: '2023-10-03' },
  { id: 'm8', s1: 's12', s2: 's14', budgetScore: 90, lifestyleScore: 90, housingScore: 85, overallScore: 88, status: 'Pending', matchedOn: '2023-10-05' },
  { id: 'm9', s1: 's5', s2: 's13', budgetScore: 95, lifestyleScore: 90, housingScore: 80, overallScore: 86, status: 'Accepted', matchedOn: '2023-09-20' },
  { id: 'm10', s1: 's18', s2: 's4', budgetScore: 85, lifestyleScore: 80, housingScore: 95, overallScore: 85, status: 'Pending', matchedOn: '2023-10-06' }
];

export const BOOKINGS = [
  { id: 'b1', studentId: 's2', propertyId: 'p1', date: '2023-10-10', status: 'Approved', type: 'Visit Requested' },
  { id: 'b2', studentId: 's1', propertyId: 'p1', date: '2023-10-12', status: 'Pending', type: 'Reservation' },
  { id: 'b3', studentId: 's4', propertyId: 'p7', date: '2023-09-15', status: 'Completed', type: 'Reservation' },
  { id: 'b4', studentId: 's5', propertyId: 'p9', date: '2023-09-18', status: 'Completed', type: 'Reservation' },
  { id: 'b5', studentId: 's8', propertyId: 'p7', date: '2023-09-20', status: 'Completed', type: 'Reservation' },
  { id: 'b6', studentId: 's9', propertyId: 'p13', date: '2023-10-05', status: 'Approved', type: 'Visit Requested' },
  { id: 'b7', studentId: 's10', propertyId: 'p12', date: '2023-09-25', status: 'Completed', type: 'Reservation' },
  { id: 'b8', studentId: 's13', propertyId: 'p9', date: '2023-09-26', status: 'Completed', type: 'Reservation' },
  { id: 'b9', studentId: 's19', propertyId: 'p1', date: '2023-10-07', status: 'Pending', type: 'Visit Requested' },
  { id: 'b10', studentId: 's20', propertyId: 'p5', date: '2023-10-08', status: 'Rejected', type: 'Reservation' }
];

export const LEASES = [
  { id: 'L101', studentId: 's4', propertyId: 'p7', startDate: '2023-10-01', endDate: '2024-09-30', rent: 12000, deposit: 24000, status: 'Active' },
  { id: 'L102', studentId: 's5', propertyId: 'p9', startDate: '2023-10-01', endDate: '2024-09-30', rent: 8800, deposit: 17600, status: 'Active' },
  { id: 'L103', studentId: 's8', propertyId: 'p7', startDate: '2023-10-01', endDate: '2024-09-30', rent: 12000, deposit: 24000, status: 'Active' },
  { id: 'L104', studentId: 's10', propertyId: 'p12', startDate: '2023-10-01', endDate: '2024-09-30', rent: 7800, deposit: 15600, status: 'Active' },
  { id: 'L105', studentId: 's13', propertyId: 'p9', startDate: '2023-10-01', endDate: '2024-09-30', rent: 8800, deposit: 17600, status: 'Active' },
  { id: 'L106', studentId: 's18', propertyId: 'p15', startDate: '2022-09-01', endDate: '2023-08-31', rent: 15000, deposit: 30000, status: 'Expired' },
  { id: 'L107', studentId: 's15', propertyId: 'p3', startDate: '2023-10-01', endDate: '2024-09-30', rent: 11000, deposit: 22000, status: 'Active' },
  { id: 'L108', studentId: 's6', propertyId: 'p11', startDate: '2022-09-01', endDate: '2023-08-31', rent: 6500, deposit: 13000, status: 'Expired' }
];

export const REVIEWS = [
  { id: 'r1', leaseId: 'L106', propertyId: 'p15', rating: 5, comment: 'Amazing place, totally worth the money.', date: '2023-09-05' },
  { id: 'r2', leaseId: 'L108', propertyId: 'p11', rating: 4, comment: 'Good flat but maintenance could be better.', date: '2023-09-10' },
  { id: 'r3', leaseId: 'none', propertyId: 'p1', rating: 5, comment: 'Visited the property, looks exactly like the pictures.', date: '2023-08-15' },
  { id: 'r4', leaseId: 'none', propertyId: 'p4', rating: 4, comment: 'Nice amenities but quite far from campus.', date: '2023-08-20' },
  { id: 'r5', leaseId: 'none', propertyId: 'p14', rating: 3, comment: 'Affordable but lacks basic facilities.', date: '2023-07-10' },
  { id: 'r6', leaseId: 'none', propertyId: 'p10', rating: 5, comment: 'Best location for JKLU students. Highly recommend!', date: '2023-09-01' },
  { id: 'r7', leaseId: 'none', propertyId: 'p3', rating: 5, comment: 'Perfect for someone who prefers a quiet environment.', date: '2023-09-12' },
  { id: 'r8', leaseId: 'none', propertyId: 'p12', rating: 4, comment: 'Safe and secure for female students. Landlord is helpful.', date: '2023-08-25' },
  { id: 'r9', leaseId: 'none', propertyId: 'p5', rating: 4, comment: 'Very close to university, saves a lot of travel time.', date: '2023-08-30' },
  { id: 'r10', leaseId: 'none', propertyId: 'p6', rating: 5, comment: 'Spacious rooms and good ventilation.', date: '2023-09-05' }
];

export const LANDLORDS = [
  { id: 'l1', name: 'Ramesh Singh', email: 'ramesh.s@example.com', verified: true, phone: '9876543210' },
  { id: 'l2', name: 'Sunita Sharma', email: 'sunita.s@example.com', verified: true, phone: '9876543211' },
  { id: 'l3', name: 'Amit Desai', email: 'amit.d@example.com', verified: true, phone: '9876543212' },
  { id: 'l4', name: 'Vikram Chawla', email: 'vikram.c@example.com', verified: false, phone: '9876543213' },
  { id: 'l5', name: 'Priya Agarwal', email: 'priya.a@example.com', verified: true, phone: '9876543214' }
];

// Helper functions for mock data processing
export const calculateTrueCost = (property: any) => {
  return property.rent + property.electricity + property.internet + property.maintenance;
};
