-- ==============================================================================================
-- UNINEST SUPABASE (POSTGRESQL) SCHEMA
-- Copy and paste this entire script into your Supabase SQL Editor and hit "Run".
-- ==============================================================================================

-- 1. CLEANUP (Drop existing objects if they exist to allow clean re-runs)
DROP VIEW IF EXISTS TOP_HOUSING_OPTIONS CASCADE;
DROP VIEW IF EXISTS STUDENT_ROOMMATE_RECOMMENDATIONS CASCADE;
DROP VIEW IF EXISTS HOUSING_RECOMMENDATIONS CASCADE;
DROP VIEW IF EXISTS AVAILABLE_PROPERTIES CASCADE;

DROP TABLE IF EXISTS REVIEW CASCADE;
DROP TABLE IF EXISTS LEASE CASCADE;
DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS ROOMMATE_MATCH CASCADE;
DROP TABLE IF EXISTS STUDENT_PREFERENCE CASCADE;
DROP TABLE IF EXISTS PROPERTY_AMENITY CASCADE;
DROP TABLE IF EXISTS AMENITY CASCADE;
DROP TABLE IF EXISTS PROPERTY CASCADE;
DROP TABLE IF EXISTS LANDLORD CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;

-- 2. TABLES & CONSTRAINTS

CREATE TABLE STUDENT (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    college_name VARCHAR(150) NOT NULL,
    college_email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    course VARCHAR(100),
    year INT,
    gender VARCHAR(20),
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED'))
);

CREATE TABLE LANDLORD (
    landlord_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(150) UNIQUE NOT NULL,
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED'))
);

CREATE TABLE PROPERTY (
    property_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id INT NOT NULL REFERENCES LANDLORD(landlord_id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    property_type VARCHAR(50) NOT NULL,
    location VARCHAR(150) NOT NULL,
    distance_from_college NUMERIC(5,2) NOT NULL CHECK (distance_from_college >= 0),
    rent_per_person NUMERIC(10,2) NOT NULL CHECK (rent_per_person > 0),
    deposit NUMERIC(10,2) NOT NULL CHECK (deposit >= 0),
    electricity_estimate NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (electricity_estimate >= 0),
    internet_cost NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (internet_cost >= 0),
    maintenance_cost NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (maintenance_cost >= 0),
    total_capacity INT NOT NULL CHECK (total_capacity > 0),
    available_slots INT NOT NULL,
    available_from DATE NOT NULL,
    gender_preference VARCHAR(20),
    furnished_status VARCHAR(50),
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED')),
    rating NUMERIC(3,2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT chk_avail CHECK (available_slots >= 0 AND available_slots <= total_capacity)
);

CREATE TABLE AMENITY (
    amenity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenity_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE PROPERTY_AMENITY (
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    amenity_id INT NOT NULL REFERENCES AMENITY(amenity_id) ON DELETE CASCADE,
    PRIMARY KEY(property_id, amenity_id)
);

CREATE TABLE STUDENT_PREFERENCE (
    preference_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT UNIQUE NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    min_budget NUMERIC(10,2),
    max_budget NUMERIC(10,2),
    max_distance NUMERIC(5,2),
    preferred_room_type VARCHAR(50),
    preferred_gender VARCHAR(20),
    move_in_date DATE,
    sleep_time TIME,
    wake_time TIME,
    cleanliness_level INT CHECK (cleanliness_level BETWEEN 1 AND 5),
    noise_tolerance INT CHECK (noise_tolerance BETWEEN 1 AND 5),
    study_habit INT CHECK (study_habit BETWEEN 1 AND 5),
    food_preference VARCHAR(50),
    smoking_preference VARCHAR(20),
    guest_preference INT CHECK (guest_preference BETWEEN 1 AND 5),
    ac_preference BOOLEAN,
    CONSTRAINT chk_pref_budget CHECK (min_budget >= 0 AND max_budget >= min_budget)
);

CREATE TABLE ROOMMATE_MATCH (
    match_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_1 INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    student_id_2 INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    compatibility_score NUMERIC(5,2) DEFAULT 0 CHECK (compatibility_score BETWEEN 0 AND 100),
    budget_score NUMERIC(5,2) DEFAULT 0 CHECK (budget_score BETWEEN 0 AND 100),
    lifestyle_score NUMERIC(5,2) DEFAULT 0 CHECK (lifestyle_score BETWEEN 0 AND 100),
    housing_score NUMERIC(5,2) DEFAULT 0 CHECK (housing_score BETWEEN 0 AND 100),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED')),
    matched_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_match_diff CHECK (student_id_1 != student_id_2),
    UNIQUE(student_id_1, student_id_2) -- Needed for upserts
);

CREATE TABLE BOOKING (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    visit_date DATE,
    booking_type VARCHAR(20) NOT NULL CHECK (booking_type IN ('VISIT', 'RESERVE')),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE LEASE (
    lease_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_rent NUMERIC(10,2) NOT NULL CHECK (monthly_rent > 0),
    security_deposit NUMERIC(10,2) NOT NULL CHECK (security_deposit >= 0),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'TERMINATED')),
    CONSTRAINT chk_lease_dates CHECK (end_date > start_date)
);

CREATE TABLE REVIEW (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    lease_id INT NOT NULL REFERENCES LEASE(lease_id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    cleanliness_rating INT CHECK (cleanliness_rating BETWEEN 1 AND 5),
    safety_rating INT CHECK (safety_rating BETWEEN 1 AND 5),
    owner_rating INT CHECK (owner_rating BETWEEN 1 AND 5),
    internet_rating INT CHECK (internet_rating BETWEEN 1 AND 5),
    comment TEXT,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. INDEXES
CREATE INDEX idx_student_email ON STUDENT(college_email);
CREATE INDEX idx_property_landlord ON PROPERTY(landlord_id);
CREATE INDEX idx_property_type ON PROPERTY(property_type);
CREATE INDEX idx_property_loc ON PROPERTY(location);
CREATE INDEX idx_property_dist ON PROPERTY(distance_from_college);
CREATE INDEX idx_property_rent ON PROPERTY(rent_per_person);
CREATE INDEX idx_property_avail ON PROPERTY(available_slots);
CREATE INDEX idx_property_status ON PROPERTY(verification_status);
CREATE INDEX idx_booking_student ON BOOKING(student_id);
CREATE INDEX idx_booking_property ON BOOKING(property_id);
CREATE INDEX idx_booking_status ON BOOKING(status);
CREATE INDEX idx_lease_student ON LEASE(student_id);
CREATE INDEX idx_lease_property ON LEASE(property_id);
CREATE INDEX idx_lease_status ON LEASE(status);
CREATE INDEX idx_review_property ON REVIEW(property_id);
CREATE INDEX idx_match_stu1 ON ROOMMATE_MATCH(student_id_1);
CREATE INDEX idx_match_stu2 ON ROOMMATE_MATCH(student_id_2);


-- 4. VIEWS
CREATE OR REPLACE VIEW AVAILABLE_PROPERTIES AS
SELECT 
    p.property_id, p.title, p.property_type, p.location, p.distance_from_college,
    p.rent_per_person, p.available_slots, p.gender_preference, p.rating,
    l.name AS landlord_name, l.phone AS landlord_phone
FROM PROPERTY p
JOIN LANDLORD l ON p.landlord_id = l.landlord_id
WHERE p.verification_status = 'VERIFIED' AND p.available_slots > 0;

CREATE OR REPLACE VIEW HOUSING_RECOMMENDATIONS AS
SELECT 
    p.property_id, p.title AS property, p.rent_per_person AS rent,
    p.electricity_estimate AS electricity, p.internet_cost AS internet, p.maintenance_cost AS maintenance,
    (p.rent_per_person + p.electricity_estimate + p.internet_cost + p.maintenance_cost) AS true_monthly_cost,
    p.distance_from_college AS distance, p.rating, p.verification_status AS verification, p.available_slots AS availability,
    ROUND(
        (p.rating / 5.0 * 40) +
        (GREATEST(0, 30000 - (p.rent_per_person + p.electricity_estimate + p.internet_cost + p.maintenance_cost)) / 30000 * 30) +
        (GREATEST(0, 15 - p.distance_from_college) / 15 * 30)
    , 2) AS housing_score
FROM PROPERTY p;

CREATE OR REPLACE VIEW STUDENT_ROOMMATE_RECOMMENDATIONS AS
SELECT
    rm.match_id, s1.student_id AS student_1_id, s1.name AS student_1_name,
    s2.student_id AS student_2_id, s2.name AS student_2_name,
    rm.compatibility_score, rm.budget_score, rm.lifestyle_score, rm.housing_score, rm.status, rm.matched_on
FROM ROOMMATE_MATCH rm
JOIN STUDENT s1 ON rm.student_id_1 = s1.student_id
JOIN STUDENT s2 ON rm.student_id_2 = s2.student_id
ORDER BY rm.compatibility_score DESC;

CREATE OR REPLACE VIEW TOP_HOUSING_OPTIONS AS
SELECT 
    s.student_id, hr.property_id, hr.property, hr.true_monthly_cost, hr.housing_score,
    rm.student_id_2 AS roommate_id, s2.name AS roommate_name,
    rm.compatibility_score AS roommate_score,
    ROUND((0.60 * hr.housing_score) + (0.40 * COALESCE(rm.compatibility_score, 0)), 2) AS overall_score
FROM STUDENT s
CROSS JOIN HOUSING_RECOMMENDATIONS hr
LEFT JOIN ROOMMATE_MATCH rm ON s.student_id = rm.student_id_1
LEFT JOIN STUDENT s2 ON rm.student_id_2 = s2.student_id
WHERE hr.verification = 'VERIFIED' AND hr.availability > 0;


-- 5. FUNCTIONS & TRIGGERS (PostgreSQL specific)

CREATE OR REPLACE FUNCTION trg_booking_approve_func()
RETURNS TRIGGER AS $$
DECLARE
    current_slots INT;
BEGIN
    IF NEW.status = 'APPROVED' AND OLD.status != 'APPROVED' THEN
        SELECT available_slots INTO current_slots FROM PROPERTY WHERE property_id = NEW.property_id;
        IF current_slots <= 0 THEN
            RAISE EXCEPTION 'Cannot approve booking: No slots available.';
        ELSE
            UPDATE PROPERTY SET available_slots = available_slots - 1 WHERE property_id = NEW.property_id;
        END IF;
    END IF;
    
    IF NEW.status = 'CANCELLED' AND OLD.status = 'APPROVED' THEN
        UPDATE PROPERTY SET available_slots = available_slots + 1 WHERE property_id = NEW.property_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_booking_approve
BEFORE UPDATE ON BOOKING
FOR EACH ROW EXECUTE FUNCTION trg_booking_approve_func();


CREATE OR REPLACE FUNCTION trg_lease_create_func()
RETURNS TRIGGER AS $$
DECLARE
    current_slots INT;
BEGIN
    SELECT available_slots INTO current_slots FROM PROPERTY WHERE property_id = NEW.property_id;
    IF current_slots <= 0 THEN
        RAISE EXCEPTION 'Cannot create lease: No slots available.';
    ELSE
        UPDATE PROPERTY SET available_slots = available_slots - 1 WHERE property_id = NEW.property_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_lease_create
BEFORE INSERT ON LEASE
FOR EACH ROW EXECUTE FUNCTION trg_lease_create_func();


CREATE OR REPLACE FUNCTION trg_review_validate_func()
RETURNS TRIGGER AS $$
DECLARE
    valid_lease_count INT;
BEGIN
    SELECT COUNT(*) INTO valid_lease_count
    FROM LEASE 
    WHERE lease_id = NEW.lease_id 
      AND student_id = NEW.student_id 
      AND property_id = NEW.property_id
      AND status IN ('ACTIVE', 'EXPIRED', 'TERMINATED'); 

    IF valid_lease_count = 0 THEN
        RAISE EXCEPTION 'Invalid Review: No valid lease found for this student and property.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_validate
BEFORE INSERT ON REVIEW
FOR EACH ROW EXECUTE FUNCTION trg_review_validate_func();


CREATE OR REPLACE FUNCTION trg_review_update_rating_func()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE PROPERTY 
    SET rating = (SELECT COALESCE(AVG(rating), 0) FROM REVIEW WHERE property_id = NEW.property_id)
    WHERE property_id = NEW.property_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_update_rating
AFTER INSERT OR UPDATE ON REVIEW
FOR EACH ROW EXECUTE FUNCTION trg_review_update_rating_func();


-- 6. MATCHING LOGIC FUNCTION
-- Translates the procedure to a Postgres function returning void (handles insert internally)
CREATE OR REPLACE FUNCTION calculate_roommate_compatibility(p_student1_id INT, p_student2_id INT)
RETURNS VOID AS $$
DECLARE
    b_score NUMERIC(5,2) := 0;
    l_score NUMERIC(5,2) := 0;
    h_score NUMERIC(5,2) := 0;
    c_score NUMERIC(5,2) := 0;
    s1_college VARCHAR(150);
    s2_college VARCHAR(150);
    diff_clean INT;
    diff_noise INT;
    diff_study INT;
    diff_guest INT;
    pref1 RECORD;
    pref2 RECORD;
BEGIN
    SELECT college_name INTO s1_college FROM STUDENT WHERE student_id = p_student1_id;
    SELECT college_name INTO s2_college FROM STUDENT WHERE student_id = p_student2_id;

    SELECT * INTO pref1 FROM STUDENT_PREFERENCE WHERE student_id = p_student1_id;
    SELECT * INTO pref2 FROM STUDENT_PREFERENCE WHERE student_id = p_student2_id;

    IF pref1 IS NULL OR pref2 IS NULL THEN
        RETURN;
    END IF;

    IF pref1.max_budget >= pref2.min_budget AND pref2.max_budget >= pref1.min_budget THEN
        b_score := 100;
    ELSE
        b_score := 50; 
    END IF;

    diff_clean := ABS(pref1.cleanliness_level - pref2.cleanliness_level);
    diff_noise := ABS(pref1.noise_tolerance - pref2.noise_tolerance);
    diff_study := ABS(pref1.study_habit - pref2.study_habit);
    diff_guest := ABS(pref1.guest_preference - pref2.guest_preference);

    l_score := 100 - (diff_clean * 5) - (diff_noise * 5) - (diff_study * 5) - (diff_guest * 5);
    
    IF pref1.food_preference = pref2.food_preference THEN
        l_score := l_score + 10;
    END IF;
    
    IF pref1.smoking_preference = pref2.smoking_preference THEN
        l_score := l_score + 10;
    END IF;

    IF l_score > 100 THEN l_score := 100; END IF;

    IF pref1.preferred_room_type = pref2.preferred_room_type THEN
        h_score := 100;
    ELSE
        h_score := 50;
    END IF;

    c_score := (b_score * 0.20) + (l_score * 0.75) + (h_score * 0.05);

    IF s1_college = s2_college THEN
        c_score := LEAST(100, c_score + 5.0);
    END IF;

    INSERT INTO ROOMMATE_MATCH (student_id_1, student_id_2, compatibility_score, budget_score, lifestyle_score, housing_score)
    VALUES (p_student1_id, p_student2_id, c_score, b_score, l_score, h_score)
    ON CONFLICT (student_id_1, student_id_2) DO UPDATE SET
        compatibility_score = EXCLUDED.compatibility_score,
        budget_score = EXCLUDED.budget_score,
        lifestyle_score = EXCLUDED.lifestyle_score,
        housing_score = EXCLUDED.housing_score;
END;
$$ LANGUAGE plpgsql;


-- 7. SEED DATA
INSERT INTO LANDLORD (name, phone, email, verification_status) VALUES
('Ramesh Kumar', '9876543210', 'ramesh@example.com', 'VERIFIED'),
('Suresh Singh', '9876543211', 'suresh@example.com', 'VERIFIED'),
('Amit Verma', '9876543212', 'amit@example.com', 'PENDING'),
('Neha Sharma', '9876543213', 'neha@example.com', 'VERIFIED'),
('Vikas Gupta', '9876543214', 'vikas@example.com', 'VERIFIED');

INSERT INTO PROPERTY (landlord_id, title, property_type, location, distance_from_college, rent_per_person, deposit, electricity_estimate, internet_cost, maintenance_cost, total_capacity, available_slots, available_from, gender_preference, furnished_status, verification_status, rating) VALUES
(1, 'Sunrise PG', 'PG', 'Bapu Nagar', 2.5, 6500, 13000, 500, 200, 300, 10, 5, '2023-08-01', 'MALE', 'Furnished', 'VERIFIED', 4.5),
(2, 'Cozy Home', '1BHK', 'Mansarovar', 4.0, 12000, 24000, 800, 400, 500, 2, 2, '2023-08-15', 'ANY', 'Semi-furnished', 'VERIFIED', 4.2),
(1, 'Elite Girls PG', 'PG', 'Malviya Nagar', 1.5, 8000, 16000, 600, 200, 400, 15, 3, '2023-07-20', 'FEMALE', 'Furnished', 'VERIFIED', 4.8),
(3, 'Students Inn', 'Shared Room', 'Ajmer Road', 1.0, 5000, 10000, 300, 150, 200, 20, 10, '2023-08-05', 'MALE', 'Furnished', 'PENDING', 3.5),
(4, 'Luxury 2BHK', '2BHK', 'Vaishali Nagar', 5.5, 18000, 36000, 1000, 500, 800, 4, 4, '2023-09-01', 'ANY', 'Furnished', 'VERIFIED', 4.9);

INSERT INTO AMENITY (amenity_name, description) VALUES
('Wi-Fi', 'High-speed internet'), ('AC', 'Air conditioning'), ('TV', 'Television'),
('Bed', 'Comfortable bed'), ('Study Table', 'Desk for studying'), ('Parking', 'Dedicated parking space'),
('Washing Machine', 'Laundry facility'), ('Kitchen', 'Access to kitchen'), ('Power Backup', '24x7 electricity backup'),
('Attached Bathroom', 'Private washroom'), ('Gym', 'Fitness center'), ('Refrigerator', 'Fridge for storage'),
('RO Water', 'Purified drinking water'), ('Security', 'CCTV and guard'), ('Housekeeping', 'Daily cleaning'),
('Balcony', 'Outdoor balcony');

INSERT INTO PROPERTY_AMENITY (property_id, amenity_id) VALUES
(1, 1), (1, 4), (1, 5), (1, 13), (1, 15),
(2, 1), (2, 8), (2, 16),
(3, 1), (3, 2), (3, 4), (3, 5), (3, 7), (3, 9), (3, 10), (3, 13), (3, 14), (3, 15),
(4, 4), (4, 5), (4, 13),
(5, 1), (5, 2), (5, 3), (5, 4), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11), (5, 12), (5, 14), (5, 16);

INSERT INTO STUDENT (name, college_name, college_email, phone, course, year, gender, verification_status) VALUES
('Rahul Sharma', 'JK Lakshmipat University', 'rahul.s@jklu.edu.in', '9123456780', 'B.Tech CS', 2, 'MALE', 'VERIFIED'),
('Priya Singh', 'JK Lakshmipat University', 'priya.s@jklu.edu.in', '9123456781', 'BBA', 1, 'FEMALE', 'VERIFIED'),
('Aman Verma', 'Manipal University', 'aman.v@jaipur.manipal.edu', '9123456782', 'B.Tech IT', 3, 'MALE', 'VERIFIED'),
('Kirti Desai', 'JK Lakshmipat University', 'kirti.d@jklu.edu.in', '9123456783', 'B.Des', 2, 'FEMALE', 'PENDING'),
('Rohan Kapoor', 'JK Lakshmipat University', 'rohan.k@jklu.edu.in', '9123456784', 'B.Tech CS', 2, 'MALE', 'VERIFIED');

INSERT INTO STUDENT_PREFERENCE (student_id, min_budget, max_budget, max_distance, preferred_room_type, preferred_gender, move_in_date, sleep_time, wake_time, cleanliness_level, noise_tolerance, study_habit, food_preference, smoking_preference, guest_preference, ac_preference) VALUES
(1, 5000, 8000, 3.0, 'PG', 'MALE', '2023-08-01', '23:00:00', '07:00:00', 4, 3, 4, 'VEG', 'NON_SMOKER', 3, false),
(2, 6000, 10000, 2.0, 'PG', 'FEMALE', '2023-07-25', '22:30:00', '06:30:00', 5, 2, 5, 'VEG', 'NON_SMOKER', 2, true),
(3, 4000, 6000, 5.0, 'Shared Room', 'MALE', '2023-08-10', '01:00:00', '09:00:00', 3, 5, 2, 'NON_VEG', 'SMOKER', 5, false),
(4, 7000, 15000, 4.0, '1BHK', 'FEMALE', '2023-08-20', '00:00:00', '08:00:00', 4, 4, 3, 'ANY', 'NON_SMOKER', 4, true),
(5, 5000, 8500, 3.5, 'PG', 'MALE', '2023-08-05', '23:30:00', '07:30:00', 4, 3, 4, 'VEG', 'NON_SMOKER', 3, false);

INSERT INTO BOOKING (student_id, property_id, booking_date, visit_date, booking_type, status) VALUES
(1, 1, '2023-07-15 10:00:00', '2023-07-16', 'VISIT', 'COMPLETED'),
(1, 1, '2023-07-17 11:00:00', NULL, 'RESERVE', 'APPROVED'),
(2, 3, '2023-07-18 09:00:00', NULL, 'RESERVE', 'APPROVED');

INSERT INTO LEASE (student_id, property_id, start_date, end_date, monthly_rent, security_deposit, status) VALUES
(1, 1, '2023-08-01', '2024-07-31', 6500, 13000, 'ACTIVE'),
(2, 3, '2023-07-25', '2024-07-24', 8000, 16000, 'ACTIVE');

INSERT INTO REVIEW (student_id, property_id, lease_id, rating, cleanliness_rating, safety_rating, owner_rating, internet_rating, comment) VALUES
(1, 1, 1, 4, 4, 5, 4, 3, 'Good PG, close to college. Food is okay.'),
(2, 3, 2, 5, 5, 5, 5, 4, 'Very safe and clean. Highly recommended for girls.');

-- Calculate some initial matches
SELECT calculate_roommate_compatibility(1, 5);
SELECT calculate_roommate_compatibility(1, 3);
