-- ==============================================================================================
-- UNINEST SUPABASE (POSTGRESQL) SCHEMA
-- Copy and paste this entire script into your Supabase SQL Editor and hit "Run".
-- ==============================================================================================

-- 1. CLEANUP (Drop existing objects if they exist to allow clean re-runs)
DROP VIEW IF EXISTS TOP_HOUSING_OPTIONS CASCADE;
DROP VIEW IF EXISTS STUDENT_ROOMMATE_RECOMMENDATIONS CASCADE;
DROP VIEW IF EXISTS HOUSING_RECOMMENDATIONS CASCADE;
DROP VIEW IF EXISTS AVAILABLE_PROPERTIES CASCADE;

DROP TABLE IF EXISTS REVIEW CASCADE;
DROP TABLE IF EXISTS LEASE CASCADE;
DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS ROOMMATE_MATCH CASCADE;
DROP TABLE IF EXISTS STUDENT_PREFERENCE CASCADE;
DROP TABLE IF EXISTS PROPERTY_AMENITY CASCADE;
DROP TABLE IF EXISTS AMENITY CASCADE;
DROP TABLE IF EXISTS PROPERTY CASCADE;
DROP TABLE IF EXISTS LANDLORD CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;

-- 2. TABLES & CONSTRAINTS

CREATE TABLE STUDENT (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    college_name VARCHAR(150) NOT NULL,
    college_email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    course VARCHAR(100),
    year INT,
    gender VARCHAR(20),
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED'))
);

CREATE TABLE LANDLORD (
    landlord_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(150) UNIQUE NOT NULL,
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED'))
);

CREATE TABLE PROPERTY (
    property_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id INT NOT NULL REFERENCES LANDLORD(landlord_id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    property_type VARCHAR(50) NOT NULL,
    location VARCHAR(150) NOT NULL,
    distance_from_college NUMERIC(5,2) NOT NULL CHECK (distance_from_college >= 0),
    rent_per_person NUMERIC(10,2) NOT NULL CHECK (rent_per_person > 0),
    deposit NUMERIC(10,2) NOT NULL CHECK (deposit >= 0),
    electricity_estimate NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (electricity_estimate >= 0),
    internet_cost NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (internet_cost >= 0),
    maintenance_cost NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (maintenance_cost >= 0),
    total_capacity INT NOT NULL CHECK (total_capacity > 0),
    available_slots INT NOT NULL,
    available_from DATE NOT NULL,
    gender_preference VARCHAR(20),
    furnished_status VARCHAR(50),
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED')),
    rating NUMERIC(3,2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT chk_avail CHECK (available_slots >= 0 AND available_slots <= total_capacity)
);

CREATE TABLE AMENITY (
    amenity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenity_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE PROPERTY_AMENITY (
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    amenity_id INT NOT NULL REFERENCES AMENITY(amenity_id) ON DELETE CASCADE,
    PRIMARY KEY(property_id, amenity_id)
);

CREATE TABLE STUDENT_PREFERENCE (
    preference_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT UNIQUE NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    min_budget NUMERIC(10,2),
    max_budget NUMERIC(10,2),
    max_distance NUMERIC(5,2),
    preferred_room_type VARCHAR(50),
    preferred_gender VARCHAR(20),
    move_in_date DATE,
    sleep_time TIME,
    wake_time TIME,
    cleanliness_level INT CHECK (cleanliness_level BETWEEN 1 AND 5),
    noise_tolerance INT CHECK (noise_tolerance BETWEEN 1 AND 5),
    study_habit INT CHECK (study_habit BETWEEN 1 AND 5),
    food_preference VARCHAR(50),
    smoking_preference VARCHAR(20),
    guest_preference INT CHECK (guest_preference BETWEEN 1 AND 5),
    ac_preference BOOLEAN,
    CONSTRAINT chk_pref_budget CHECK (min_budget >= 0 AND max_budget >= min_budget)
);

CREATE TABLE ROOMMATE_MATCH (
    match_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_1 INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    student_id_2 INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    compatibility_score NUMERIC(5,2) DEFAULT 0 CHECK (compatibility_score BETWEEN 0 AND 100),
    budget_score NUMERIC(5,2) DEFAULT 0 CHECK (budget_score BETWEEN 0 AND 100),
    lifestyle_score NUMERIC(5,2) DEFAULT 0 CHECK (lifestyle_score BETWEEN 0 AND 100),
    housing_score NUMERIC(5,2) DEFAULT 0 CHECK (housing_score BETWEEN 0 AND 100),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED')),
    matched_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_match_diff CHECK (student_id_1 != student_id_2),
    UNIQUE(student_id_1, student_id_2) -- Needed for upserts
);

CREATE TABLE BOOKING (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    visit_date DATE,
    booking_type VARCHAR(20) NOT NULL CHECK (booking_type IN ('VISIT', 'RESERVE')),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE LEASE (
    lease_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_rent NUMERIC(10,2) NOT NULL CHECK (monthly_rent > 0),
    security_deposit NUMERIC(10,2) NOT NULL CHECK (security_deposit >= 0),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'TERMINATED')),
    CONSTRAINT chk_lease_dates CHECK (end_date > start_date)
);

CREATE TABLE REVIEW (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES PROPERTY(property_id) ON DELETE CASCADE,
    lease_id INT NOT NULL REFERENCES LEASE(lease_id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    cleanliness_rating INT CHECK (cleanliness_rating BETWEEN 1 AND 5),
    safety_rating INT CHECK (safety_rating BETWEEN 1 AND 5),
    owner_rating INT CHECK (owner_rating BETWEEN 1 AND 5),
    internet_rating INT CHECK (internet_rating BETWEEN 1 AND 5),
    comment TEXT,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. INDEXES
CREATE INDEX idx_student_email ON STUDENT(college_email);
CREATE INDEX idx_property_landlord ON PROPERTY(landlord_id);
CREATE INDEX idx_property_type ON PROPERTY(property_type);
CREATE INDEX idx_property_loc ON PROPERTY(location);
CREATE INDEX idx_property_dist ON PROPERTY(distance_from_college);
CREATE INDEX idx_property_rent ON PROPERTY(rent_per_person);
CREATE INDEX idx_property_avail ON PROPERTY(available_slots);
CREATE INDEX idx_property_status ON PROPERTY(verification_status);
CREATE INDEX idx_booking_student ON BOOKING(student_id);
CREATE INDEX idx_booking_property ON BOOKING(property_id);
CREATE INDEX idx_booking_status ON BOOKING(status);
CREATE INDEX idx_lease_student ON LEASE(student_id);
CREATE INDEX idx_lease_property ON LEASE(property_id);
CREATE INDEX idx_lease_status ON LEASE(status);
CREATE INDEX idx_review_property ON REVIEW(property_id);
CREATE INDEX idx_match_stu1 ON ROOMMATE_MATCH(student_id_1);
CREATE INDEX idx_match_stu2 ON ROOMMATE_MATCH(student_id_2);


-- 4. VIEWS
CREATE OR REPLACE VIEW AVAILABLE_PROPERTIES AS
SELECT 
    p.property_id, p.title, p.property_type, p.location, p.distance_from_college,
    p.rent_per_person, p.available_slots, p.gender_preference, p.rating,
    l.name AS landlord_name, l.phone AS landlord_phone
FROM PROPERTY p
JOIN LANDLORD l ON p.landlord_id = l.landlord_id
WHERE p.verification_status = 'VERIFIED' AND p.available_slots > 0;

CREATE OR REPLACE VIEW HOUSING_RECOMMENDATIONS AS
SELECT 
    p.property_id, p.title AS property, p.rent_per_person AS rent,
    p.electricity_estimate AS electricity, p.internet_cost AS internet, p.maintenance_cost AS maintenance,
    (p.rent_per_person + p.electricity_estimate + p.internet_cost + p.maintenance_cost) AS true_monthly_cost,
    p.distance_from_college AS distance, p.rating, p.verification_status AS verification, p.available_slots AS availability,
    ROUND(
        (p.rating / 5.0 * 40) +
        (GREATEST(0, 30000 - (p.rent_per_person + p.electricity_estimate + p.internet_cost + p.maintenance_cost)) / 30000 * 30) +
        (GREATEST(0, 15 - p.distance_from_college) / 15 * 30)
    , 2) AS housing_score
FROM PROPERTY p;

CREATE OR REPLACE VIEW STUDENT_ROOMMATE_RECOMMENDATIONS AS
SELECT
    rm.match_id, s1.student_id AS student_1_id, s1.name AS student_1_name,
    s2.student_id AS student_2_id, s2.name AS student_2_name,
    rm.compatibility_score, rm.budget_score, rm.lifestyle_score, rm.housing_score, rm.status, rm.matched_on
FROM ROOMMATE_MATCH rm
JOIN STUDENT s1 ON rm.student_id_1 = s1.student_id
JOIN STUDENT s2 ON rm.student_id_2 = s2.student_id
ORDER BY rm.compatibility_score DESC;

CREATE OR REPLACE VIEW TOP_HOUSING_OPTIONS AS
SELECT 
    s.student_id, hr.property_id, hr.property, hr.true_monthly_cost, hr.housing_score,
    rm.student_id_2 AS roommate_id, s2.name AS roommate_name,
    rm.compatibility_score AS roommate_score,
    ROUND((0.60 * hr.housing_score) + (0.40 * COALESCE(rm.compatibility_score, 0)), 2) AS overall_score
FROM STUDENT s
CROSS JOIN HOUSING_RECOMMENDATIONS hr
LEFT JOIN ROOMMATE_MATCH rm ON s.student_id = rm.student_id_1
LEFT JOIN STUDENT s2 ON rm.student_id_2 = s2.student_id
WHERE hr.verification = 'VERIFIED' AND hr.availability > 0;


-- 5. FUNCTIONS & TRIGGERS (PostgreSQL specific)

CREATE OR REPLACE FUNCTION trg_booking_approve_func()
RETURNS TRIGGER AS $$
DECLARE
    current_slots INT;
BEGIN
    IF NEW.status = 'APPROVED' AND OLD.status != 'APPROVED' THEN
        SELECT available_slots INTO current_slots FROM PROPERTY WHERE property_id = NEW.property_id;
        IF current_slots <= 0 THEN
            RAISE EXCEPTION 'Cannot approve booking: No slots available.';
        ELSE
            UPDATE PROPERTY SET available_slots = available_slots - 1 WHERE property_id = NEW.property_id;
        END IF;
    END IF;
    
    IF NEW.status = 'CANCELLED' AND OLD.status = 'APPROVED' THEN
        UPDATE PROPERTY SET available_slots = available_slots + 1 WHERE property_id = NEW.property_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_booking_approve
BEFORE UPDATE ON BOOKING
FOR EACH ROW EXECUTE FUNCTION trg_booking_approve_func();


CREATE OR REPLACE FUNCTION trg_lease_create_func()
RETURNS TRIGGER AS $$
DECLARE
    current_slots INT;
BEGIN
    SELECT available_slots INTO current_slots FROM PROPERTY WHERE property_id = NEW.property_id;
    IF current_slots <= 0 THEN
        RAISE EXCEPTION 'Cannot create lease: No slots available.';
    ELSE
        UPDATE PROPERTY SET available_slots = available_slots - 1 WHERE property_id = NEW.property_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_lease_create
BEFORE INSERT ON LEASE
FOR EACH ROW EXECUTE FUNCTION trg_lease_create_func();


CREATE OR REPLACE FUNCTION trg_review_validate_func()
RETURNS TRIGGER AS $$
DECLARE
    valid_lease_count INT;
BEGIN
    SELECT COUNT(*) INTO valid_lease_count
    FROM LEASE 
    WHERE lease_id = NEW.lease_id 
      AND student_id = NEW.student_id 
      AND property_id = NEW.property_id
      AND status IN ('ACTIVE', 'EXPIRED', 'TERMINATED'); 

    IF valid_lease_count = 0 THEN
        RAISE EXCEPTION 'Invalid Review: No valid lease found for this student and property.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_validate
BEFORE INSERT ON REVIEW
FOR EACH ROW EXECUTE FUNCTION trg_review_validate_func();


CREATE OR REPLACE FUNCTION trg_review_update_rating_func()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE PROPERTY 
    SET rating = (SELECT COALESCE(AVG(rating), 0) FROM REVIEW WHERE property_id = NEW.property_id)
    WHERE property_id = NEW.property_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_update_rating
AFTER INSERT OR UPDATE ON REVIEW
FOR EACH ROW EXECUTE FUNCTION trg_review_update_rating_func();


-- 6. MATCHING LOGIC FUNCTION
-- Translates the procedure to a Postgres function returning void (handles insert internally)
CREATE OR REPLACE FUNCTION calculate_roommate_compatibility(p_student1_id INT, p_student2_id INT)
RETURNS VOID AS $$
DECLARE
    b_score NUMERIC(5,2) := 0;
    l_score NUMERIC(5,2) := 0;
    h_score NUMERIC(5,2) := 0;
    c_score NUMERIC(5,2) := 0;
    s1_college VARCHAR(150);
    s2_college VARCHAR(150);
    diff_clean INT;
    diff_noise INT;
    diff_study INT;
    diff_guest INT;
    pref1 RECORD;
    pref2 RECORD;
BEGIN
    SELECT college_name INTO s1_college FROM STUDENT WHERE student_id = p_student1_id;
    SELECT college_name INTO s2_college FROM STUDENT WHERE student_id = p_student2_id;

    SELECT * INTO pref1 FROM STUDENT_PREFERENCE WHERE student_id = p_student1_id;
    SELECT * INTO pref2 FROM STUDENT_PREFERENCE WHERE student_id = p_student2_id;

    IF pref1 IS NULL OR pref2 IS NULL THEN
        RETURN;
    END IF;

    IF pref1.max_budget >= pref2.min_budget AND pref2.max_budget >= pref1.min_budget THEN
        b_score := 100;
    ELSE
        b_score := 50; 
    END IF;

    diff_clean := ABS(pref1.cleanliness_level - pref2.cleanliness_level);
    diff_noise := ABS(pref1.noise_tolerance - pref2.noise_tolerance);
    diff_study := ABS(pref1.study_habit - pref2.study_habit);
    diff_guest := ABS(pref1.guest_preference - pref2.guest_preference);

    l_score := 100 - (diff_clean * 5) - (diff_noise * 5) - (diff_study * 5) - (diff_guest * 5);
    
    IF pref1.food_preference = pref2.food_preference THEN
        l_score := l_score + 10;
    END IF;
    
    IF pref1.smoking_preference = pref2.smoking_preference THEN
        l_score := l_score + 10;
    END IF;

    IF l_score > 100 THEN l_score := 100; END IF;

    IF pref1.preferred_room_type = pref2.preferred_room_type THEN
        h_score := 100;
    ELSE
        h_score := 50;
    END IF;

    c_score := (b_score * 0.20) + (l_score * 0.75) + (h_score * 0.05);

    IF s1_college = s2_college THEN
        c_score := LEAST(100, c_score + 5.0);
    END IF;

    INSERT INTO ROOMMATE_MATCH (student_id_1, student_id_2, compatibility_score, budget_score, lifestyle_score, housing_score)
    VALUES (p_student1_id, p_student2_id, c_score, b_score, l_score, h_score)
    ON CONFLICT (student_id_1, student_id_2) DO UPDATE SET
        compatibility_score = EXCLUDED.compatibility_score,
        budget_score = EXCLUDED.budget_score,
        lifestyle_score = EXCLUDED.lifestyle_score,
        housing_score = EXCLUDED.housing_score;
END;
$$ LANGUAGE plpgsql;


